version: '3'

networks:
  db:

services:
  postgres:
    container_name: desafio_star_wars
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: star_wars
      POSTGRES_USER: jedi
      POSTGRES_PASSWORD: sabre-luz
      MAX_CONNECTIONS: 300
    networks:
      - db